services:
  personal-website:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: personal-website
    restart: unless-stopped
    expose:
      - 80
    labels:
      - diun.watch=true
      - traefik.enable=true
      - traefik.http.routers.personal-website.entrypoints=websecure
      - traefik.http.routers.personal-website.rule=Host(`${DOMAIN_NAME}`) || Host(`www.${DOMAIN_NAME}`)
      - traefik.http.routers.personal-website.middlewares=chain-no-auth@file
      - traefik.http.services.personal-website.loadbalancer.server.port=80
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy_default
