name: Analyse
on:
  push:
    branches:

jobs:
  analyse:
    name: Analyse
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install npm dependencies
        run: npm ci
      - name: Lint
        run: npm run lint --if-present
      - name: Lint fix
        run: npm run lint:fix --if-present
