name: Build
on:
  push:
    branches:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Set up Node
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version-file: .nvmrc
          cache: npm
      
      - name: Install npm dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present
      
      - name: Test
        run: npm test
